### ISSUE TITLE
blender

### ISSUE THREAD

**Issue by tin-ku** [stuffmatic/fSpy-Blender#84]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1388, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2452, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2583, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\startup\bl_operators\userpref.py", line 821, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: invalid syntax (__init__.py, line 23)
Modules Installed () from 'C:\\Users\\Asus\\Downloads\\fSpy-Blender-1.0.3.zip' into 'C:\\Users\\Asus\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\scripts\\addons'

**Comment by thelabcat** [comment]
This appears to be a bug in Blender itself. You should report it to their development team, if it hasn't already been fixed (please test).

**Comment by thelabcat** [comment]
Related to #81
